### PR TITLE
Update schema naming to avoid confusion

### PR DESCRIPTION
**Pull request by vicbergquist**
I've updated the schema name of `project` to `sampleProject` to make it clearer that it's a generic schema name and can be changed depending on your own needs and to avoid confusion.

I've tested it and I think I managed to change it in all the right places, but if someone more familiar with this template could double check, I think that would be great.

### CODE REVIEW

**Comment by bjoerge** [comment]
There seems to be an schema error here: image

https://deploy-preview-30--sanity-template-gatsby-portfolio-studio.netlify.com/dashboard

This also means we need to update the exported sample dataset, I presume?

**Comment by vicbergquist** [comment]
> There seems to be an schema error here: image
> 
> https://deploy-preview-30--sanity-template-gatsby-portfolio-studio.netlify.com/dashboard
> 
> This also means we need to update the exported sample dataset, I presume?

Oops true! Thanks! Fixed.

**Comment by evenwestvang** [comment]
I'm all 👍 about the naming change. 🏹

**Comment by vicbergquist** [comment]
How can I restart the build for this to see if it's working?

**Comment by kmelve** [comment]
I think you'll have to push a fix for it?

**Comment by evenwestvang** [comment]
@jemmima I think this was started, but never completed?

**Comment by kmelve** [comment]
Everything with the studio and data was as it should be, but there were some GraphQL queries in the frontend that had escaped the renaming and hence broke the build. Pushed a fix for it now!

**Comment by vicbergquist** [comment]
Thanks Knut! 🙏

**Comment by evenwestvang** [comment]
Great! Thank you to both of you for clarifying and 🚢ing!

**Pull request merged**
